### ISSUE TITLE
Support Polymer 2.0

### ISSUE THREAD

**Issue by samuelli** [webcomponents/webcomponents.org#913]
### Required changes

- [x] Run analyzer on all packages #756 
- [x] Run side by side client replacement #923 
- [x] Update client to support analyzer output #932 
- [x] Match existing styling #942 
- [x] Fix performance #942 
- [x] Fix search document indexing to support analyzer #932 
- [x] Use analyzer by default #962 
- [x] Disable hydrolysis for faster build #961 

### External dependencies
- [x] Show inherited/private checkboxes https://github.com/PolymerElements/iron-doc-viewer/issues/123
- [x] Demo list parity https://github.com/Polymer/polymer-analyzer/issues/626

**Comment by samuelli** [comment]
For anyone that might be following along. You can preview Polymer 2.0 by appending `?analyzer` to the URL. Let me know if there's any feedback/bugs.

**Comment by samuelli** [comment]
External dependencies on https://github.com/PolymerElements/iron-doc-viewer/issues/123 and https://github.com/Polymer/polymer-analyzer/issues/626.
